
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjITicket.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Comment()
    {

        this.CommentReport = new HashSet<CommentReport>();

    }


    public int CommentID { get; set; }

    public int CommentMemberID { get; set; }

    public int CommentActivityId { get; set; }

    public string CommentContent { get; set; }

    public int CommentScore { get; set; }

    public System.DateTime CommentDate { get; set; }

    public bool IsBaned { get; set; }



    public virtual Activity Activity { get; set; }

    public virtual Member Member { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CommentReport> CommentReport { get; set; }

}

}
