
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjITicket.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Member
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member()
    {

        this.Article = new HashSet<Article>();

        this.Article_Emotion = new HashSet<Article_Emotion>();

        this.Article_Report = new HashSet<Article_Report>();

        this.BanLIst = new HashSet<BanLIst>();

        this.BanLIst1 = new HashSet<BanLIst>();

        this.Comment = new HashSet<Comment>();

        this.Orders = new HashSet<Orders>();

        this.Reply_Emotion = new HashSet<Reply_Emotion>();

        this.Reply = new HashSet<Reply>();

        this.Reply_Report = new HashSet<Reply_Report>();

        this.Seller = new HashSet<Seller>();

        this.ShoppingCart = new HashSet<ShoppingCart>();

        this.ShortMessage = new HashSet<ShortMessage>();

        this.Subscribes = new HashSet<Subscribes>();

        this.ActivityFavourite = new HashSet<ActivityFavourite>();

        this.CommentReport = new HashSet<CommentReport>();

    }


    public int MemberID { get; set; }

    public string Email { get; set; }

    public string Name { get; set; }

    public string IDentityNumber { get; set; }

    public string Passport { get; set; }

    public string NickName { get; set; }

    public Nullable<System.DateTime> BirthDate { get; set; }

    public string Phone { get; set; }

    public string Password { get; set; }

    public int Point { get; set; }

    public string Address { get; set; }

    public int MemberRoleId { get; set; }

    public string Icon { get; set; }

    public Nullable<bool> Sex { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public string RegisterCheckCode { get; set; }

    public string provider { get; set; }

    public Nullable<bool> providerFB { get; set; }

    public Nullable<bool> providerGO { get; set; }

    public Nullable<System.DateTime> fRegister_time { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Article> Article { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Article_Emotion> Article_Emotion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Article_Report> Article_Report { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BanLIst> BanLIst { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BanLIst> BanLIst1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comment> Comment { get; set; }

    public virtual Districts Districts { get; set; }

    public virtual MemberRole MemberRole { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Orders> Orders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reply_Emotion> Reply_Emotion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reply> Reply { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reply_Report> Reply_Report { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Seller> Seller { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShortMessage> ShortMessage { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Subscribes> Subscribes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ActivityFavourite> ActivityFavourite { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CommentReport> CommentReport { get; set; }

}

}
