
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjITicket.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Reply
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Reply()
    {

        this.Reply_Emotion = new HashSet<Reply_Emotion>();

        this.Reply_Report = new HashSet<Reply_Report>();

    }


    public int ReplyID { get; set; }

    public string ReplyContent { get; set; }

    public int MemberID { get; set; }

    public System.DateTime ReplyDate { get; set; }

    public int ArticleID { get; set; }

    public bool Readed { get; set; }



    public virtual Article Article { get; set; }

    public virtual Member Member { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reply_Emotion> Reply_Emotion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Reply_Report> Reply_Report { get; set; }

}

}
