
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjITicket.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Seller
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Seller()
    {

        this.Activity = new HashSet<Activity>();

        this.Subscribes = new HashSet<Subscribes>();

    }


    public int SellerID { get; set; }

    public string CompanyName { get; set; }

    public string TaxIDNumber { get; set; }

    public string SellerHomePage { get; set; }

    public string SellerPhone { get; set; }

    public string SellerDeccription { get; set; }

    public int MemberId { get; set; }

    public Nullable<bool> fPass { get; set; }

    public string fFileName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Activity> Activity { get; set; }

    public virtual Member Member { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Subscribes> Subscribes { get; set; }

}

}
