

//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjITicket.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TicketSysEntities : DbContext
{
    public TicketSysEntities()
        : base("name=TicketSysEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Activity> Activity { get; set; }

    public virtual DbSet<ActivityStatus> ActivityStatus { get; set; }

    public virtual DbSet<Article> Article { get; set; }

    public virtual DbSet<Article_Emotion> Article_Emotion { get; set; }

    public virtual DbSet<Article_Report> Article_Report { get; set; }

    public virtual DbSet<ArticleCategories> ArticleCategories { get; set; }

    public virtual DbSet<BanLIst> BanLIst { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<Cities> Cities { get; set; }

    public virtual DbSet<Comment> Comment { get; set; }

    public virtual DbSet<Districts> Districts { get; set; }

    public virtual DbSet<EmotionAction> EmotionAction { get; set; }

    public virtual DbSet<Member> Member { get; set; }

    public virtual DbSet<MemberRole> MemberRole { get; set; }

    public virtual DbSet<Order_Detail> Order_Detail { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<Reply> Reply { get; set; }

    public virtual DbSet<Reply_Emotion> Reply_Emotion { get; set; }

    public virtual DbSet<Reply_Report> Reply_Report { get; set; }

    public virtual DbSet<Report> Report { get; set; }

    public virtual DbSet<Seller> Seller { get; set; }

    public virtual DbSet<ShoppingCart> ShoppingCart { get; set; }

    public virtual DbSet<ShortMessage> ShortMessage { get; set; }

    public virtual DbSet<SubCategories> SubCategories { get; set; }

    public virtual DbSet<Subscribes> Subscribes { get; set; }

    public virtual DbSet<TicketCategory> TicketCategory { get; set; }

    public virtual DbSet<TicketGroupDetail> TicketGroupDetail { get; set; }

    public virtual DbSet<TicketGroups> TicketGroups { get; set; }

    public virtual DbSet<TicketQRCodes> TicketQRCodes { get; set; }

    public virtual DbSet<Tickets> Tickets { get; set; }

    public virtual DbSet<TicketTimes> TicketTimes { get; set; }

    public virtual DbSet<ActivityFavourite> ActivityFavourite { get; set; }

    public virtual DbSet<ActivityFailedReason> ActivityFailedReason { get; set; }

    public virtual DbSet<Ad_Article_Activity> Ad_Article_Activity { get; set; }

    public virtual DbSet<CommentReport> CommentReport { get; set; }

}

}

