
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace prjITicket.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tickets
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tickets()
    {

        this.Order_Detail = new HashSet<Order_Detail>();

        this.ShoppingCart = new HashSet<ShoppingCart>();

    }


    public int TicketID { get; set; }

    public int TicketCategoryId { get; set; }

    public int Price { get; set; }

    public int UnitsInStock { get; set; }

    public int ActivityID { get; set; }

    public int TicketTimeId { get; set; }

    public decimal Discount { get; set; }



    public virtual Activity Activity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order_Detail> Order_Detail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }

    public virtual TicketCategory TicketCategory { get; set; }

    public virtual TicketTimes TicketTimes { get; set; }

}

}
